export const UI_COPY = {
  appName: 'ShipTrack',
  nav: {
    adminDashboard: 'ภาพรวมการจัดส่ง',
    messengerDashboard: 'งานจัดส่ง',
    create: 'สร้างรายการส่ง',
    track: 'ติดตามสถานะ',
    parcelActivity: 'ประวัติพัสดุ',
    auditLogs: 'บันทึกระบบ',
    users: 'จัดการพนักงาน',
    staffLogin: 'เข้าสู่ระบบพนักงาน',
  },
  parcel: {
    trackingId: 'หมายเลขติดตาม',
    itemDetail: 'รายละเอียดสิ่งที่ส่ง',
    proofPhoto: 'หลักฐานการจัดส่ง',
    origin: 'ต้นทาง',
    destination: 'ปลายทาง',
    sender: 'ผู้ส่ง',
    receiver: 'ผู้รับ',
    recipient: 'ส่งให้',
    routeHistory: 'ประวัติการจัดส่ง',
  },
  action: {
    create: 'สร้างรายการ',
    search: 'ค้นหา',
    track: 'ติดตามสถานะ',
    acceptJob: 'รับงาน',
    completeDelivery: 'ยืนยันการจัดส่ง',
    confirmCompleteDelivery: 'ยืนยันการจัดส่ง',
    releaseJob: 'คืนงาน',
    history: 'ประวัติ',
    retakePhoto: 'ถ่ายใหม่',
    removePhoto: 'ลบรูป',
  },
} as const;
